### ISSUE TITLE
Added a PV Sensor and now power is unknown

### ISSUE THREAD

**Issue by scott40k** [custom-components/sensor.owlintuition#13]
Hi,

I've just added a solar sensor to my setup but now the -electricity sensors have stopped getting data if I set the yaml back to just having -electricity it works again. 

Almost like the addition of -solar means the last option is what is used rather than both solar and electricity

**Comment by glpatcern** [comment]
Hi,

This behavior seems to have some similarity with #5, and could be due to the OWL hub getting both data updates at nearly the same time.

To validate that, could you try to modify the code at https://github.com/custom-components/sensor.owlintuition/blob/master/custom_components/owlintuition/sensor.py#L161 with `secs = 1` or even `secs = 0`?

**Comment by scott40k** [comment]
Hi,

 

I managed to get this working by removing and reinstalling the Integration in HACS

 

Thanks

 

Scott Read

**Comment by glpatcern** [comment]
Ah, that's interesting, good that the code did not need to be modified.

Cheers
